version: '3.7'

services:
  aiogram_template:
    build:
      context: .
      dockerfile: .ci/Dockerfile
    container_name: aiogram_template
    environment:
      - TELEGRAM_API_KEY=$TELEGRAM_API_KEY
    env_file:
      - .env
