name: linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      - name: Install dependencies
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip wheel setuptools poetry
          poetry config virtualenvs.create false
          poetry install --no-root --no-interaction
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Analysing the code with flake8
        run: |
          make lint
  safety:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
      - name: Analysing the dependencies with safety
        run: |
          make safety
